#!/bin/sh
set -e

if [ "$1" = "configure" ]
then
  groupadd -r thingsplex || true
  groupadd -r sensibo || true

  useradd -r -N -M -d / -s /bin/false -g thingsplex sensibo || true

  chown -R sensibo:thingsplex /var/log/thingsplex/sensibo/sensibo.log || true
  chown -R sensibo:sensibo /opt/thingsplex/sensibo/ || true
fi

deb-systemd-helper unmask sensibo.service >/dev/null || true

if deb-systemd-helper --quiet was-enabled sensibo.service; then
  systemctl enable sensibo.service || true
else
  deb-systemd-helper update-state sensibo.service >/dev/null || true
fi

if [ -d /run/systemd/system ]; then
  systemctl --system daemon-reload >/dev/null || true

  if [ -n "$2" ]; then
    deb-systemd-invoke try-restart sensibo.service >/dev/null || true
  else
    deb-systemd-invoke start sensibo.service >/dev/null || true
  fi
fi