#!/bin/sh
set -e

if [ -d /run/systemd/system ]; then
  systemctl --system daemon-reload >/dev/null || true
fi

if [ "$1" = "remove" ]; then
  if [ -x "/usr/bin/deb-systemd-helper" ]; then
    deb-systemd-helper mask sensibo.service >/dev/null
  fi
fi

if [ "$1" = "purge" ]; then
  if [ -x "/usr/bin/deb-systemd-helper" ]; then
    deb-systemd-helper purge sensibo.service >/dev/null
    deb-systemd-helper unmask sensibo.service >/dev/null
  fi
fi
