#!/bin/sh
set -e

if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
  deb-systemd-invoke stop sensibo.service >/dev/null
  systemctl disable sensibo.service || true
  rm /var/log/thingsplex/sensibo/* || true
fi